apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-aws-kubernetes-platform
  namespace: tx-pts-dai
  description: terraform-aws-kubernetes-platform component
  annotations:
    github.com/project-slug: tx-pts-dai/terraform-aws-kubernetes-platform
    backstage.io/techdocs-ref: dir:.
  tags:
    - tx-pts-dai
spec:
  type: infrastructure
  lifecycle: production
  owner: group:default/dai