containerRuntime: containerd
operator:
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi
fluentbit:
  enabled: true
  priorityClassName: system-node-critical
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - arm64
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
  filter:
    kubernetes:
      enable: true
      labels: true
      annotations: true
    containerd:
      enable: true
    multiline:
      enable: true
      parsers:
        - go
        - python
        - java
        - java-multiline
  input:
    tail:
      enable: true
  parsers:
    javaMultiline:
      enable: true
