containerRuntime: containerd
operator:
  priorityClassName: system-cluster-critical
fluentbit:
  priorityClassName: system-node-critical
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - arm64
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
  # Because we deploy our own pipeline, disable the default one
  filter:
    kubernetes:
      enable: false # true = default
    containerd:
      enable: true # If disabled, fluent-operator has reconciler error
  input:
    tail:
      enable: false # true = default
