name: Manual Destroy Pull Request Deployments

on:
  workflow_dispatch:
    inputs:
      tf_dir:
        description: 'Example directory'
        required: true
        default: 'examples/complete'
        type: choice
        options:
          - examples/complete
          - examples/datadog
          - examples/disable-addons
          - examples/lacework
          - examples/network
          - examples/simple

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete:
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v3
    with:
      environment: examples
      tf_dir: ${{ inputs.tf_dir }}
      tf_workspace: ${{ github.ref_name }}
