name: Destroy Pull Request Deployments

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete:
    strategy:
      fail-fast: false
      matrix:
        directory:
          - examples/lacework
          - examples/complete

    uses: tx-pts-dai/github-workflows/.github/workflows/tf-cleanup.yaml@v0.16.0
    with:
      environment: examples
      tf_dir: ${{ matrix.directory }}
