name: Destroy Pull Request Deployments

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete:
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-dflook-cleanup.yaml@v0.8.0
    with:
      environment: examples
      tf_backend_configs: |
        bucket=tf-state-911453050078
        key=example/complete.tfstate
        workspace_key_prefix=terraform-aws-kubernetes-platform
      tf_dir: examples/complete
