name: Deploy Module Examples - Complete

on:
  pull_request:
    paths:
      - '.github/workflows/examples-complete.yaml'
      - 'examples/complete/**'
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:    
      - 'renovate_**'


permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete_deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-feature.yaml@v0.16.0
    with:
      environment: examples
      tf_dir: examples/complete

  example_complete_destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-cleanup.yaml@v0.16.0
    with:
      environment: examples
      tf_dir: examples/complete
