name: Deploy Module Examples - datadog

# since is not needed every time and requires the datadog api and app keys this workflow is on dispatch
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_datadog_deploy:
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-feature.yaml@v0.16.0
    with:
      environment: examples
      tf_dir: examples/datadog
