name: Module Example - Simple

on:
  pull_request:
    paths:
      - examples/simple/*.tf
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:
      - renovate**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_simple_deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-feature.yaml@v0.24.0
    with:
      environment: examples
      tf_dir: examples/simple

  example_simple_destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-cleanup.yaml@v0.24.0
    with:
      environment: examples
      tf_dir: examples/simple
