name: Deploy Module Examples - Complete

on:
  pull_request:
    paths:
      - 'examples/complete/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete:
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-dflook-feature.yaml@v0.10.0
    with:
      environment: examples
      tf_dir: examples/complete
      tf_vars: |
        cluster_admins = {
          sso = {
            role_name = "aws-reserved/sso.amazonaws.com/eu-west-1/AWSReservedSSO_AWSAdministratorAccess_3cb2c900c0e65cd2"
          }
          cicd = {
            role_name = "cicd-iac"
          }
        }
