name: Module Example - Complete

on:
  pull_request:
    paths:
      - examples/complete/*.tf
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:
      - renovate/*

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete_deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-feature.yaml@v2
    with:
      environment: examples
      tf_dir: examples/complete

  example_complete_destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v2
    with:
      environment: examples
      tf_dir: examples/complete
