name: Module Example - Disable Addons

on:
  pull_request:
    paths:
      - examples/disable-addons/*.tf
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:
      - renovate/*

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  example_disable_addons_deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-feature.yaml@v3
    with:
      environment: examples
      tf_dir: examples/disable-addons

  example_disabled_addons_destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v3
    with:
      environment: examples
      tf_dir: examples/disable-addons
