name: Deploy Module Examples

on:
  pull_request:
    paths:
      - 'examples/complete/**'
      - '.github/workflows/examples.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  example_complete:
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-dflook-feature.yaml@v0.10.0
    with:
      environment: examples
      tf_backend_configs: |
        bucket=tf-state-911453050078
        key=examples/complete.tfstate
        workspace_key_prefix=terraform-aws-kubernetes-platform
      tf_dir: examples/complete
