name: Manual Destroy Feature Branch Test

on:
  workflow_dispatch:
    inputs:
      tf_dir:
        description: 'Directory'
        required: true
        default: 'tests/main'
        type: choice
        options:
          - tests/main

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  destroy_feature:
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v3
    with:
      environment: examples
      tf_dir: ${{ inputs.tf_dir }}
