# This is a test workflow to run pre-commit hooks on a branch created by renovate
name: Generate terraform docs

on:
  push:
    branches:
      - renovate**
    paths:
      - "**.tf"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: .
        recursive: true
        git-push: "true"
